coverage:
  status:
    project:
      default:
        target: 70%          # Minimum overall coverage
        threshold: 5%        # Allow 5% drop before failing
    patch:
      default:
        target: 80%          # New code must be 80% covered

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/node_modules/**"
