sonar.projectKey=yassineAbdellatif_Git-happens
sonar.organization=githappens

# Project information
sonar.projectName=Git-happens
sonar.projectVersion=1.0

# Source code paths
sonar.sources=app
sonar.tests=tests

# Exclude from analysis
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,**/dist/**,**/build/**,**/__mocks__/**

# Test coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage/integration/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info,coverage/integration/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/tests/**,**/screens/**,**/components/**,**/styles/**,**/navigation/**,**/context/**,**/types/**,**/hooks/useMapLogic.ts,**/hooks/useCalendarLogic.ts,**/hooks/useNextClass.ts,**/auth/**,app/frontend/App.tsx,app/frontend/index.ts,app/backend/src/index.ts,**/calendarListService.ts,**/calendarService.ts

# Pull Request decoration
sonar.pullrequest.provider=github
sonar.pullrequest.github.repository=yassineAbdellatif/Git-happens

# Source encoding
sonar.sourceEncoding=UTF-8