import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f8f8",
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  header: {
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    paddingTop: 50,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    flex: 1,
    textAlign: "center",
  },
  weekRangeText: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
    marginTop: 2,
  },
  backButtonSmall: {
    padding: 8,
  },
  refreshButton: {
    padding: 8,
  },
  weekNavigationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  weekNavButton: {
    padding: 8,
  },
  todayButtonText: {
    color: "#912338",
    fontWeight: "bold",
    fontSize: 14,
  },
  scrollView: {
    flex: 1,
  },
  calendarContainer: {
    backgroundColor: "white",
  },
  dayHeaderRow: {
    flexDirection: "row",
    borderBottomWidth: 2,
    borderBottomColor: "#912338",
  },
  timeColumnHeader: {
    width: 45,
  },
  dayColumn: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    borderRightWidth: 1,
    borderRightColor: "#eee",
  },
  dayName: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
  },
  dayDate: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#912338",
    marginTop: 2,
  },
  timeSlotRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    minHeight: 60,
  },
  timeLabel: {
    width: 45,
    justifyContent: "flex-start",
    paddingVertical: 4,
    paddingHorizontal: 4,
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#eee",
  },
  timeLabelText: {
    fontSize: 10,
    color: "#666",
    fontWeight: "600",
  },
  dayCell: {
    flex: 1,
    position: "relative",
    borderRightWidth: 1,
    borderRightColor: "#eee",
    minHeight: 60,
  },
  eventBlock: {
    position: "absolute",
    left: 2,
    right: 2,
    backgroundColor: "#912338",
    borderRadius: 6,
    padding: 4,
    opacity: 0.85,
    zIndex: 10,
    elevation: 3,
  },
  eventBlockTitle: {
    fontSize: 10,
    fontWeight: "bold",
    color: "white",
    marginBottom: 2,
  },
  eventBlockTime: {
    fontSize: 8,
    color: "rgba(255, 255, 255, 0.9)",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginTop: 12,
    paddingHorizontal: 24,
  },
  hint: {
    fontSize: 12,
    color: "#999",
    textAlign: "center",
    marginTop: 16,
    fontStyle: "italic",
  },
  loadingText: {
    fontSize: 14,
    color: "#666",
    marginTop: 12,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  retryButton: {
    backgroundColor: "#912338",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  retryButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  backButton: {
    backgroundColor: "#666",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  backButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  modalContainer: {
    width: "100%",
    maxWidth: 270,
    backgroundColor: "white",
    borderRadius: 12,
    padding: 14,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  modalTime: {
    marginTop: 6,
    fontSize: 15,
    color: "#912338",
    fontWeight: "600",
    textAlign: "center",
  },
  modalDetailText: {
    marginTop: 8,
    fontSize: 15,
    color: "#555",
    lineHeight: 22,
    textAlign: "center",
  },
  modalDirectionsButton: {
    marginTop: 14,
    alignSelf: "center",
    backgroundColor: "#912338",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  modalDirectionsButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  modalDirectionsIcon: {
    width: 18,
    height: 18,
    marginLeft: 8,
  },
  modalDirectionsButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 15,
    textAlign: "center",
  },
  modalCloseButton: {
    marginTop: 8,
    alignSelf: "flex-end",
    backgroundColor: "#912338",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  modalCloseButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 15,
    textAlign: "center",
  },
});
