export type IndoorBuildingId = "H" | "CC";

export type FloorNumber = "1" | "2" | "8" | "9";

export type LocalizedNodeType =
  | "entrance"
  | "elevator"
  | "stairs"
  | "washroom"
  | "classroom";

export interface LocalizedNode {
  id: string;
  label: string;
  nodeType: LocalizedNodeType;
  x: number;
  y: number;
}

export interface FloorPlanRegistryEntry {
  buildingId: IndoorBuildingId;
  floorNumber: FloorNumber;
  floorPlanFile: string;
  localizedNodes: LocalizedNode[];
}

export interface IndoorGraphMeta {
  buildingId: string;
}

export interface IndoorGraphNode {
  id: string;
  type: string;
  buildingId: string;
  floor: number;
  x: number;
  y: number;
  label: string;
  accessible: boolean;
}

export interface IndoorGraphEdge {
  source: string;
  target: string;
  type: string;
  weight: number;
  accessible: boolean;
}

export interface IndoorGraphData {
  meta: IndoorGraphMeta;
  nodes: IndoorGraphNode[];
  edges: IndoorGraphEdge[];
}

const SUPPORTED_INDOOR_BUILDINGS: readonly IndoorBuildingId[] = ["H", "CC"];

const isSupportedIndoorBuildingId = (
  buildingId: string,
): buildingId is IndoorBuildingId =>
  SUPPORTED_INDOOR_BUILDINGS.includes(buildingId as IndoorBuildingId);

const FLOOR_PLAN_REGISTRY: FloorPlanRegistryEntry[] = [
  {
    buildingId: "H",
    floorNumber: "1",
    floorPlanFile: "assets/updated_floor_plans/h1.png",
    localizedNodes: [
      {
        id: "H1-ENT-S",
        label: "H1 South Entrance",
        nodeType: "entrance",
        x: 1032,
        y: 1460,
      },
      {
        id: "H1-ENT-E",
        label: "H1 East Entrance",
        nodeType: "entrance",
        x: 1370,
        y: 672,
      },
      {
        id: "H1-ELEV-1",
        label: "H1 Elevator Bank",
        nodeType: "elevator",
        x: 761,
        y: 1020,
      },
      {
        id: "H1-STAIR-1",
        label: "H1 West Stair Core",
        nodeType: "stairs",
        x: 173,
        y: 708,
      },
      {
        id: "H1-STAIR-2",
        label: "H1 East Stair Core",
        nodeType: "stairs",
        x: 1355,
        y: 534,
      },
      {
        id: "H1-STAIR-3",
        label: "H1 South Stair Core",
        nodeType: "stairs",
        x: 823,
        y: 1212,
      },
      {
        id: "H1-WC-1",
        label: "H1 North Washroom Cluster",
        nodeType: "washroom",
        x: 1039,
        y: 227,
      },
      {
        id: "H1-WC-2",
        label: "H1 Central Washroom Cluster",
        nodeType: "washroom",
        x: 759,
        y: 536,
      },
      {
        id: "H1-ROOM-150",
        label: "H1 Classroom 150",
        nodeType: "classroom",
        x: 1083,
        y: 684,
      },
      {
        id: "H1-ROOM-141",
        label: "H1 Room 141",
        nodeType: "classroom",
        x: 1328,
        y: 77,
      },
      {
        id: "H1-ROOM-133",
        label: "H1 Room 133",
        nodeType: "classroom",
        x: 863,
        y: 151,
      },
      {
        id: "H1-ROOM-127",
        label: "H1 Room 127",
        nodeType: "classroom",
        x: 70,
        y: 366,
      },
      {
        id: "H1-ROOM-125",
        label: "H1 Room 125",
        nodeType: "classroom",
        x: 67,
        y: 522,
      },
      {
        id: "H1-ROOM-120",
        label: "H1 Room 120",
        nodeType: "classroom",
        x: 635,
        y: 664,
      },
      {
        id: "H1-ROOM-115",
        label: "H1 Room 115",
        nodeType: "classroom",
        x: 875,
        y: 808,
      },
      {
        id: "H1-ROOM-116",
        label: "H1 Room 116",
        nodeType: "classroom",
        x: 855,
        y: 1000,
      },
      {
        id: "H1-ROOM-110",
        label: "H1 Classroom 110",
        nodeType: "classroom",
        x: 381,
        y: 842,
      },
      {
        id: "H1-ROOM-102",
        label: "H1 Classroom 102",
        nodeType: "classroom",
        x: 1183,
        y: 1206,
      },
      {
        id: "H1-ROOM-101",
        label: "H1 Room 101",
        nodeType: "classroom",
        x: 1303,
        y: 1333,
      },
    ],
  },
  {
    buildingId: "H",
    floorNumber: "2",
    floorPlanFile: "assets/updated_floor_plans/h2.png",
    localizedNodes: [
      {
        id: "H2-ENT-NW",
        label: "H2 North-West Entrance",
        nodeType: "entrance",
        x: 25,
        y: 37,
      },
      {
        id: "H2-ENT-E",
        label: "H2 East Entrance",
        nodeType: "entrance",
        x: 1322,
        y: 336,
      },
      {
        id: "H2-ENT-S",
        label: "H2 South Entrance",
        nodeType: "entrance",
        x: 1269,
        y: 1464,
      },
      {
        id: "H2-ELEV-1",
        label: "H2 Elevator Bank",
        nodeType: "elevator",
        x: 906,
        y: 925,
      },
      {
        id: "H2-STAIR-1",
        label: "H2 North-West Stair Core",
        nodeType: "stairs",
        x: 47,
        y: 42,
      },
      {
        id: "H2-STAIR-2",
        label: "H2 East Stair Core",
        nodeType: "stairs",
        x: 1266,
        y: 666,
      },
      {
        id: "H2-STAIR-3",
        label: "H2 South-East Stair Core",
        nodeType: "stairs",
        x: 1189,
        y: 975,
      },
      {
        id: "H2-STAIR-4",
        label: "H2 West Mid Stair Core",
        nodeType: "stairs",
        x: 83,
        y: 737,
      },
      {
        id: "H2-WC-1",
        label: "H2 Upper Central Washroom Cluster",
        nodeType: "washroom",
        x: 640,
        y: 244,
      },
      {
        id: "H2-WC-2",
        label: "H2 Lower Central Washroom Cluster",
        nodeType: "washroom",
        x: 579,
        y: 287,
      },
      {
        id: "H2-ROOM-290",
        label: "H2 Room 290",
        nodeType: "classroom",
        x: 88,
        y: 572,
      },
      {
        id: "H2-ROOM-280",
        label: "H2 Room 280",
        nodeType: "classroom",
        x: 1276,
        y: 446,
      },
      {
        id: "H2-ROOM-239",
        label: "H2 Room 239",
        nodeType: "classroom",
        x: 749,
        y: 182,
      },
      {
        id: "H2-ROOM-231",
        label: "H2 Room 231",
        nodeType: "classroom",
        x: 524,
        y: 182,
      },
      {
        id: "H2-ROOM-230",
        label: "H2 Room 230",
        nodeType: "classroom",
        x: 486,
        y: 267,
      },
      {
        id: "H2-ROOM-222",
        label: "H2 Room 222",
        nodeType: "classroom",
        x: 1125,
        y: 440,
      },
      {
        id: "H2-ROOM-220",
        label: "H2 Room 220",
        nodeType: "classroom",
        x: 1029,
        y: 443,
      },
      {
        id: "H2-ROOM-205",
        label: "H2 Room 205",
        nodeType: "classroom",
        x: 188,
        y: 575,
      },
      {
        id: "H2-ROOM-110",
        label: "H2 Classroom 110",
        nodeType: "classroom",
        x: 390,
        y: 829,
      },
      {
        id: "H2-ROOM-108",
        label: "H2 Room 108",
        nodeType: "classroom",
        x: 613,
        y: 1371,
      },
    ],
  },
  {
    buildingId: "H",
    floorNumber: "8",
    floorPlanFile: "assets/updated_floor_plans/h8.png",
    localizedNodes: [
      {
        id: "H8-ENT-W",
        label: "H8 West Corridor Access",
        nodeType: "entrance",
        x: 300,
        y: 740,
      },
      {
        id: "H8-ENT-E",
        label: "H8 East Corridor Access",
        nodeType: "entrance",
        x: 1315,
        y: 740,
      },
      {
        id: "H8-ELEV-1",
        label: "H8 West Elevator A",
        nodeType: "elevator",
        x: 578,
        y: 499,
      },
      {
        id: "H8-ELEV-2",
        label: "H8 West Elevator B",
        nodeType: "elevator",
        x: 626,
        y: 499,
      },
      {
        id: "H8-STAIR-1",
        label: "H8 West Stair Core",
        nodeType: "stairs",
        x: 498,
        y: 493,
      },
      {
        id: "H8-STAIR-2",
        label: "H8 North-East Stair Core",
        nodeType: "stairs",
        x: 1130,
        y: 334,
      },
      {
        id: "H8-STAIR-3",
        label: "H8 South-East Stair Core",
        nodeType: "stairs",
        x: 1134,
        y: 1111,
      },
      {
        id: "H8-STAIR-4",
        label: "H8 South-West Stair Core",
        nodeType: "stairs",
        x: 500,
        y: 1116,
      },
      {
        id: "H8-WC-1",
        label: "H8 Washroom West",
        nodeType: "washroom",
        x: 616,
        y: 339,
      },
      {
        id: "H8-WC-2",
        label: "H8 Washroom East",
        nodeType: "washroom",
        x: 1079,
        y: 337,
      },
      {
        id: "H8-ROOM-867",
        label: "H8 Room 867",
        nodeType: "classroom",
        x: 128,
        y: 90,
      },
      {
        id: "H8-ROOM-803",
        label: "H8 Room 803",
        nodeType: "classroom",
        x: 503,
        y: 86,
      },
      {
        id: "H8-ROOM-811",
        label: "H8 Room 811",
        nodeType: "classroom",
        x: 1068,
        y: 87,
      },
      {
        id: "H8-ROOM-817",
        label: "H8 Room 817",
        nodeType: "classroom",
        x: 1519,
        y: 89,
      },
      {
        id: "H8-ROOM-802",
        label: "H8 Room 802",
        nodeType: "classroom",
        x: 562,
        y: 361,
      },
      {
        id: "H8-ROOM-810",
        label: "H8 Room 810",
        nodeType: "classroom",
        x: 1018,
        y: 368,
      },
      {
        id: "H8-ROOM-820",
        label: "H8 Room 820",
        nodeType: "classroom",
        x: 1030,
        y: 707,
      },
      {
        id: "H8-ROOM-822",
        label: "H8 Room 822",
        nodeType: "classroom",
        x: 1193,
        y: 900,
      },
      {
        id: "H8-ROOM-862",
        label: "H8 Room 862",
        nodeType: "classroom",
        x: 586,
        y: 706,
      },
      {
        id: "H8-ROOM-849",
        label: "H8 Room 849",
        nodeType: "classroom",
        x: 125,
        y: 1365,
      },
      {
        id: "H8-ROOM-841",
        label: "H8 Room 841",
        nodeType: "classroom",
        x: 742,
        y: 1366,
      },
      {
        id: "H8-ROOM-831",
        label: "H8 Room 831",
        nodeType: "classroom",
        x: 1517,
        y: 1369,
      },
    ],
  },
  {
    buildingId: "H",
    floorNumber: "9",
    floorPlanFile: "assets/updated_floor_plans/h9.png",
    localizedNodes: [
      {
        id: "H9-ENT-W",
        label: "H9 West Corridor Access",
        nodeType: "entrance",
        x: 248,
        y: 748,
      },
      {
        id: "H9-ENT-E",
        label: "H9 East Corridor Access",
        nodeType: "entrance",
        x: 1491,
        y: 756,
      },
      {
        id: "H9-ELEV-1",
        label: "H9 Central Elevator A",
        nodeType: "elevator",
        x: 807,
        y: 900,
      },
      {
        id: "H9-ELEV-2",
        label: "H9 Central Elevator B",
        nodeType: "elevator",
        x: 865,
        y: 902,
      },
      {
        id: "H9-STAIR-1",
        label: "H9 North-West Stair Core",
        nodeType: "stairs",
        x: 501,
        y: 457,
      },
      {
        id: "H9-STAIR-2",
        label: "H9 North-East Stair Core",
        nodeType: "stairs",
        x: 1171,
        y: 458,
      },
      {
        id: "H9-STAIR-3",
        label: "H9 South-East Stair Core",
        nodeType: "stairs",
        x: 1225,
        y: 1016,
      },
      {
        id: "H9-STAIR-4",
        label: "H9 South-West Stair Core",
        nodeType: "stairs",
        x: 490,
        y: 1164,
      },
      {
        id: "H9-WC-1",
        label: "H9 South-West Washroom",
        nodeType: "washroom",
        x: 607,
        y: 1166,
      },
      {
        id: "H9-WC-2",
        label: "H9 South-East Washroom",
        nodeType: "washroom",
        x: 1009,
        y: 1168,
      },
      {
        id: "H9-ROOM-929",
        label: "H9 Room 929",
        nodeType: "classroom",
        x: 98,
        y: 104,
      },
      {
        id: "H9-ROOM-933",
        label: "H9 Room 933",
        nodeType: "classroom",
        x: 420,
        y: 103,
      },
      {
        id: "H9-ROOM-941",
        label: "H9 Room 941",
        nodeType: "classroom",
        x: 938,
        y: 95,
      },
      {
        id: "H9-ROOM-945",
        label: "H9 Room 945",
        nodeType: "classroom",
        x: 1137,
        y: 260,
      },
      {
        id: "H9-ROOM-980",
        label: "H9 Room 980",
        nodeType: "classroom",
        x: 576,
        y: 613,
      },
      {
        id: "H9-ROOM-920",
        label: "H9 Room 920",
        nodeType: "classroom",
        x: 614,
        y: 812,
      },
      {
        id: "H9-ROOM-910",
        label: "H9 Room 910",
        nodeType: "classroom",
        x: 605,
        y: 1094,
      },
      {
        id: "H9-ROOM-902",
        label: "H9 Room 902",
        nodeType: "classroom",
        x: 1048,
        y: 1113,
      },
      {
        id: "H9-ROOM-903",
        label: "H9 Room 903",
        nodeType: "classroom",
        x: 1175,
        y: 1405,
      },
      {
        id: "H9-ROOM-963",
        label: "H9 Room 963",
        nodeType: "classroom",
        x: 1521,
        y: 810,
      },
      {
        id: "H9-ROOM-965",
        label: "H9 Room 965",
        nodeType: "classroom",
        x: 1518,
        y: 1035,
      },
    ],
  },
  {
    buildingId: "CC",
    floorNumber: "1",
    floorPlanFile: "assets/updated_floor_plans/cc1.png",
    localizedNodes: [
      {
        id: "CC1-ENT-W",
        label: "CC1 West Entrance",
        nodeType: "entrance",
        x: 12,
        y: 378,
      },
      {
        id: "CC1-ENT-E",
        label: "CC1 East Entrance",
        nodeType: "entrance",
        x: 2596,
        y: 372,
      },
      {
        id: "CC1-ELEV-1",
        label: "CC1 Elevator Core",
        nodeType: "elevator",
        x: 1737,
        y: 283,
      },
      {
        id: "CC1-STAIR-1",
        label: "CC1 Stair Core West",
        nodeType: "stairs",
        x: 1150,
        y: 106,
      },
      {
        id: "CC1-STAIR-2",
        label: "CC1 Stair Core East",
        nodeType: "stairs",
        x: 2294,
        y: 478,
      },
      {
        id: "CC1-WC-1",
        label: "CC1 West Washroom Cluster",
        nodeType: "washroom",
        x: 169,
        y: 216,
      },
      {
        id: "CC1-WC-2",
        label: "CC1 East Washroom",
        nodeType: "washroom",
        x: 2267,
        y: 259,
      },
      {
        id: "CC1-ROOM-124",
        label: "CC1 Room 124",
        nodeType: "classroom",
        x: 146,
        y: 189,
      },
      {
        id: "CC1-ROOM-122",
        label: "CC1 Room 122",
        nodeType: "classroom",
        x: 427,
        y: 179,
      },
      {
        id: "CC1-ROOM-120",
        label: "CC1 Room 120",
        nodeType: "classroom",
        x: 709,
        y: 184,
      },
      {
        id: "CC1-ROOM-118",
        label: "CC1 Room 118",
        nodeType: "classroom",
        x: 945,
        y: 193,
      },
      {
        id: "CC1-ROOM-116",
        label: "CC1 Classroom 116",
        nodeType: "classroom",
        x: 1119,
        y: 195,
      },
      {
        id: "CC1-ROOM-112",
        label: "CC1 Room 112",
        nodeType: "classroom",
        x: 1532,
        y: 190,
      },
      {
        id: "CC1-ROOM-106",
        label: "CC1 Classroom 106",
        nodeType: "classroom",
        x: 1860,
        y: 259,
      },
      {
        id: "CC1-ROOM-104",
        label: "CC1 Room 104",
        nodeType: "classroom",
        x: 2256,
        y: 248,
      },
      {
        id: "CC1-ROOM-102",
        label: "CC1 Room 102",
        nodeType: "classroom",
        x: 2272,
        y: 344,
      },
      {
        id: "CC1-ROOM-101",
        label: "CC1 Room 101",
        nodeType: "classroom",
        x: 1849,
        y: 546,
      },
      {
        id: "CC1-ROOM-111",
        label: "CC1 Classroom 111",
        nodeType: "classroom",
        x: 1440,
        y: 546,
      },
      {
        id: "CC1-ROOM-115",
        label: "CC1 Room 115",
        nodeType: "classroom",
        x: 1038,
        y: 537,
      },
      {
        id: "CC1-ROOM-117",
        label: "CC1 Room 117",
        nodeType: "classroom",
        x: 690,
        y: 560,
      },
      {
        id: "CC1-ROOM-119",
        label: "CC1 Room 119",
        nodeType: "classroom",
        x: 375,
        y: 595,
      },
    ],
  },
];

export const getSupportedFloorsForBuilding = (
  buildingId: string,
): FloorNumber[] => {
  if (!isSupportedIndoorBuildingId(buildingId)) {
    return [];
  }

  return FLOOR_PLAN_REGISTRY.filter((entry) => entry.buildingId === buildingId)
    .map((entry) => entry.floorNumber)
    .sort();
};

export const getFloorPlanRegistryEntry = (
  buildingId: string,
  floorNumber: FloorNumber,
): FloorPlanRegistryEntry | null => {
  if (!isSupportedIndoorBuildingId(buildingId)) {
    return null;
  }

  return (
    FLOOR_PLAN_REGISTRY.find(
      (entry) =>
        entry.buildingId === buildingId && entry.floorNumber === floorNumber,
    ) || null
  );
};

export const CC_GRAPH_DATA: IndoorGraphData = {
  meta: {
    buildingId: "CC",
  },
  nodes: [
    {
      id: "CC_F1_room_224",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 1188,
      y: 645,
      label: "CC-124",
      accessible: true,
    },
    {
      id: "CC_F1_room_225",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 1688,
      y: 635,
      label: "CC-122",
      accessible: true,
    },
    {
      id: "CC_F1_room_226",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 2261,
      y: 640,
      label: "CC-120",
      accessible: true,
    },
    {
      id: "CC_F1_room_227",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 2720,
      y: 645,
      label: "CC-118",
      accessible: true,
    },
    {
      id: "CC_F1_room_228",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 3491,
      y: 606,
      label: "CC-116",
      accessible: true,
    },
    {
      id: "CC_F1_room_229",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 4618,
      y: 625,
      label: "CC-112",
      accessible: true,
    },
    {
      id: "CC_F1_room_230",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 5921,
      y: 608,
      label: "CC-106",
      accessible: true,
    },
    {
      id: "CC_F1_room_231",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 6897,
      y: 538,
      label: "CC-104",
      accessible: true,
    },
    {
      id: "CC_F1_room_232",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 7046,
      y: 833,
      label: "CC-102",
      accessible: true,
    },
    {
      id: "CC_F1_room_233",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 6368,
      y: 1448,
      label: "CC-101",
      accessible: true,
    },
    {
      id: "CC_F1_room_234",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 5521,
      y: 1299,
      label: "CC-107",
      accessible: true,
    },
    {
      id: "CC_F1_room_235",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 5414,
      y: 1496,
      label: "CC-109",
      accessible: true,
    },
    {
      id: "CC_F1_room_236",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 4633,
      y: 1453,
      label: "CC-111",
      accessible: true,
    },
    {
      id: "CC_F1_room_237",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 3506,
      y: 1467,
      label: "CC-115",
      accessible: true,
    },
    {
      id: "CC_F1_room_238",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 2696,
      y: 1470,
      label: "CC-117",
      accessible: true,
    },
    {
      id: "CC_F1_room_239",
      type: "room",
      buildingId: "CC",
      floor: 1,
      x: 1681,
      y: 1460,
      label: "CC-119",
      accessible: true,
    },
    {
      id: "CC_F1_building_entry_exit_5",
      type: "building_entry_exit",
      buildingId: "CC",
      floor: 1,
      x: 406,
      y: 995,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_245",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 717,
      y: 722,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_246",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 747,
      y: 1246,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_247",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 1349,
      y: 925,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_248",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 1371,
      y: 1186,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_249",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 1882,
      y: 923,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_250",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 1908,
      y: 1204,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_251",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 2066,
      y: 1201,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_252",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 2044,
      y: 932,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_253",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 2850,
      y: 922,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_254",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 2847,
      y: 1195,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_255",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 2489,
      y: 1201,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_256",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 2985,
      y: 947,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_257",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 3089,
      y: 1186,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_258",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 4072,
      y: 1186,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_259",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 3986,
      y: 950,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_260",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 4104,
      y: 946,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_261",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 4235,
      y: 1186,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_262",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 5152,
      y: 944,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_263",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 5146,
      y: 1177,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_264",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 5425,
      y: 962,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_265",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 5541,
      y: 1183,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_266",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 5276,
      y: 1201,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_267",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 6389,
      y: 1177,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_268",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 6368,
      y: 968,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_269",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 6725,
      y: 958,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_270",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 7285,
      y: 944,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_271",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 7462,
      y: 1204,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_272",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 7303,
      y: 1499,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_273",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 2831,
      y: 393,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_274",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 5250,
      y: 315,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_275",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 6998,
      y: 964,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_276",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 963,
      y: 1052,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_98",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 6938,
      y: 1066,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_99",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 5299,
      y: 1076,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_100",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 4050,
      y: 1073,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_101",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 2695,
      y: 1079,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_102",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 1259,
      y: 1076,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_103",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 765,
      y: 1896,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_104",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 7690,
      y: 1825,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_105",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 7654,
      y: 185,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_106",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 736,
      y: 182,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_107",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 2834,
      y: 118,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_hallway_waypoint_108",
      type: "hallway_waypoint",
      buildingId: "CC",
      floor: 1,
      x: 5244,
      y: 98,
      label: "",
      accessible: true,
    },
    {
      id: "CC_F1_doorway_277",
      type: "doorway",
      buildingId: "CC",
      floor: 1,
      x: 7086,
      y: 1068,
      label: "",
      accessible: true,
    },
  ],
  edges: [
    {
      source: "CC_F1_doorway_245",
      target: "CC_F1_building_entry_exit_5",
      type: "room_to_door",
      weight: 414,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_245",
      target: "CC_F1_doorway_276",
      type: "hallway",
      weight: 412,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_276",
      target: "CC_F1_doorway_246",
      type: "hallway",
      weight: 290,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_246",
      target: "CC_F1_building_entry_exit_5",
      type: "room_to_door",
      weight: 423,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_247",
      target: "CC_F1_room_224",
      type: "room_to_door",
      weight: 323,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_248",
      target: "CC_F1_room_239",
      type: "room_to_door",
      weight: 414,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_250",
      target: "CC_F1_room_239",
      type: "room_to_door",
      weight: 342,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_251",
      target: "CC_F1_room_239",
      type: "room_to_door",
      weight: 464,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_249",
      target: "CC_F1_room_225",
      type: "room_to_door",
      weight: 347,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_252",
      target: "CC_F1_room_226",
      type: "room_to_door",
      weight: 364,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_255",
      target: "CC_F1_room_238",
      type: "room_to_door",
      weight: 339,
      accessible: true,
    },
    {
      source: "CC_F1_room_238",
      target: "CC_F1_doorway_254",
      type: "room_to_door",
      weight: 314,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_253",
      target: "CC_F1_room_227",
      type: "room_to_door",
      weight: 306,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_273",
      target: "CC_F1_room_227",
      type: "room_to_door",
      weight: 275,
      accessible: true,
    },
    {
      source: "CC_F1_room_228",
      target: "CC_F1_doorway_256",
      type: "room_to_door",
      weight: 610,
      accessible: true,
    },
    {
      source: "CC_F1_room_228",
      target: "CC_F1_doorway_259",
      type: "room_to_door",
      weight: 603,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_260",
      target: "CC_F1_room_229",
      type: "room_to_door",
      weight: 606,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_262",
      target: "CC_F1_room_229",
      type: "room_to_door",
      weight: 622,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_261",
      target: "CC_F1_room_236",
      type: "room_to_door",
      weight: 479,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_258",
      target: "CC_F1_room_237",
      type: "room_to_door",
      weight: 632,
      accessible: true,
    },
    {
      source: "CC_F1_room_237",
      target: "CC_F1_doorway_257",
      type: "room_to_door",
      weight: 503,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_263",
      target: "CC_F1_room_236",
      type: "room_to_door",
      weight: 583,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_274",
      target: "CC_F1_room_230",
      type: "room_to_door",
      weight: 732,
      accessible: true,
    },
    {
      source: "CC_F1_room_230",
      target: "CC_F1_doorway_264",
      type: "room_to_door",
      weight: 609,
      accessible: true,
    },
    {
      source: "CC_F1_room_230",
      target: "CC_F1_doorway_268",
      type: "room_to_door",
      weight: 574,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_269",
      target: "CC_F1_room_231",
      type: "room_to_door",
      weight: 454,
      accessible: true,
    },
    {
      source: "CC_F1_room_232",
      target: "CC_F1_doorway_275",
      type: "room_to_door",
      weight: 140,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_270",
      target: "CC_F1_doorway_271",
      type: "hallway",
      weight: 315,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_271",
      target: "CC_F1_doorway_272",
      type: "hallway",
      weight: 335,
      accessible: true,
    },
    {
      source: "CC_F1_room_233",
      target: "CC_F1_doorway_267",
      type: "room_to_door",
      weight: 272,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_265",
      target: "CC_F1_room_234",
      type: "room_to_door",
      weight: 118,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_266",
      target: "CC_F1_room_235",
      type: "room_to_door",
      weight: 326,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_246",
      target: "CC_F1_hallway_waypoint_103",
      type: "door_to_hallway",
      weight: 650,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_276",
      target: "CC_F1_hallway_waypoint_102",
      type: "door_to_hallway",
      weight: 297,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_102",
      target: "CC_F1_doorway_247",
      type: "door_to_hallway",
      weight: 176,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_102",
      target: "CC_F1_doorway_248",
      type: "door_to_hallway",
      weight: 157,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_102",
      target: "CC_F1_hallway_waypoint_101",
      type: "hallway",
      weight: 1436,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_101",
      target: "CC_F1_doorway_251",
      type: "door_to_hallway",
      weight: 641,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_102",
      target: "CC_F1_doorway_250",
      type: "door_to_hallway",
      weight: 662,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_102",
      target: "CC_F1_doorway_249",
      type: "door_to_hallway",
      weight: 642,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_101",
      target: "CC_F1_doorway_252",
      type: "door_to_hallway",
      weight: 667,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_101",
      target: "CC_F1_doorway_253",
      type: "door_to_hallway",
      weight: 221,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_101",
      target: "CC_F1_doorway_255",
      type: "door_to_hallway",
      weight: 239,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_101",
      target: "CC_F1_doorway_254",
      type: "door_to_hallway",
      weight: 191,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_101",
      target: "CC_F1_doorway_256",
      type: "door_to_hallway",
      weight: 319,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_101",
      target: "CC_F1_doorway_257",
      type: "door_to_hallway",
      weight: 408,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_101",
      target: "CC_F1_hallway_waypoint_100",
      type: "hallway",
      weight: 1355,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_100",
      target: "CC_F1_doorway_259",
      type: "door_to_hallway",
      weight: 139,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_100",
      target: "CC_F1_doorway_260",
      type: "door_to_hallway",
      weight: 138,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_100",
      target: "CC_F1_doorway_261",
      type: "door_to_hallway",
      weight: 217,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_100",
      target: "CC_F1_doorway_258",
      type: "door_to_hallway",
      weight: 115,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_100",
      target: "CC_F1_doorway_256",
      type: "door_to_hallway",
      weight: 1072,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_100",
      target: "CC_F1_doorway_257",
      type: "door_to_hallway",
      weight: 968,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_100",
      target: "CC_F1_hallway_waypoint_99",
      type: "hallway",
      weight: 1249,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_99",
      target: "CC_F1_doorway_262",
      type: "door_to_hallway",
      weight: 198,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_99",
      target: "CC_F1_doorway_263",
      type: "door_to_hallway",
      weight: 183,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_99",
      target: "CC_F1_doorway_264",
      type: "door_to_hallway",
      weight: 170,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_99",
      target: "CC_F1_doorway_265",
      type: "door_to_hallway",
      weight: 265,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_99",
      target: "CC_F1_doorway_266",
      type: "door_to_hallway",
      weight: 127,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_99",
      target: "CC_F1_hallway_waypoint_98",
      type: "hallway",
      weight: 1639,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_98",
      target: "CC_F1_doorway_267",
      type: "door_to_hallway",
      weight: 560,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_98",
      target: "CC_F1_doorway_268",
      type: "door_to_hallway",
      weight: 578,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_98",
      target: "CC_F1_doorway_275",
      type: "door_to_hallway",
      weight: 118,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_98",
      target: "CC_F1_doorway_269",
      type: "door_to_hallway",
      weight: 239,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_271",
      target: "CC_F1_hallway_waypoint_104",
      type: "door_to_hallway",
      weight: 662,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_104",
      target: "CC_F1_doorway_272",
      type: "door_to_hallway",
      weight: 506,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_104",
      target: "CC_F1_hallway_waypoint_105",
      type: "hallway",
      weight: 1640,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_105",
      target: "CC_F1_doorway_271",
      type: "door_to_hallway",
      weight: 1037,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_105",
      target: "CC_F1_doorway_270",
      type: "door_to_hallway",
      weight: 844,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_105",
      target: "CC_F1_hallway_waypoint_108",
      type: "hallway",
      weight: 2412,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_108",
      target: "CC_F1_doorway_274",
      type: "door_to_hallway",
      weight: 217,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_108",
      target: "CC_F1_hallway_waypoint_107",
      type: "hallway",
      weight: 2410,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_107",
      target: "CC_F1_doorway_273",
      type: "door_to_hallway",
      weight: 275,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_107",
      target: "CC_F1_hallway_waypoint_106",
      type: "hallway",
      weight: 2099,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_106",
      target: "CC_F1_doorway_245",
      type: "door_to_hallway",
      weight: 540,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_103",
      target: "CC_F1_hallway_waypoint_104",
      type: "hallway",
      weight: 6925,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_98",
      target: "CC_F1_doorway_277",
      type: "door_to_hallway",
      weight: 148,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_277",
      target: "CC_F1_doorway_270",
      type: "hallway",
      weight: 234,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_277",
      target: "CC_F1_doorway_272",
      type: "hallway",
      weight: 483,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_99",
      target: "CC_F1_doorway_268",
      type: "door_to_hallway",
      weight: 1074,
      accessible: true,
    },
    {
      source: "CC_F1_doorway_267",
      target: "CC_F1_hallway_waypoint_99",
      type: "door_to_hallway",
      weight: 1095,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_99",
      target: "CC_F1_doorway_260",
      type: "door_to_hallway",
      weight: 1202,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_99",
      target: "CC_F1_doorway_261",
      type: "door_to_hallway",
      weight: 1070,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_102",
      target: "CC_F1_doorway_252",
      type: "door_to_hallway",
      weight: 798,
      accessible: true,
    },
    {
      source: "CC_F1_hallway_waypoint_102",
      target: "CC_F1_doorway_251",
      type: "door_to_hallway",
      weight: 817,
      accessible: true,
    },
  ],
};
